/******************************************************************************
 *
 * Module: HC-SR04 (ultrasonic sensor)
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the HC-SR04 (ultrasonic sensor) driver
 *
 * Author: Esraa Ali
 *
 *******************************************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#define ULTRASONIC_TRIGGER_PORTID PORTB_ID
#define ULTRASONIC_TRIGGER_PINID  PIN5_ID

/*include the standard types header file */
#include "std_types.h"
/*
 *  Description :1- Initialize the ICU driver as required.
                 2- Setup the ICU call back function.
                 3- Setup the direction for the trigger pin as output pin through the GPIO driver.
     Inputs      : None
     Return      : None
 * */
void Ultrasonic_init(void);

/*
• Description : Send the Trigger pulse to the ultrasonic.
• Inputs      : None
• Return      : None
 */

void Ultrasonic_Trigger(void);

/*
• Description : 1- Send the trigger pulse by using Ultrasonic_Trigger function.
                2- Start the measurements by the ICU from this moment.
• Inputs      : None
• Return      : The measured distance in cm
 */

uint16 Ultrasonic_readDistance(void);

/*
 • Description : 1-This is the call back function called by the ICU driver.
               : 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 • Inputs      : None
 • Return      : None
 */

void Ultrasonic_edgeProcessing(void);

#endif /* end of ULTRASONIC_H_*/
