/******************************************************************************
 *
 * Module: HC-SR04 (ultrasonic sensor)
 *
 * File Name: ultrasonic.c
 *
 * Description: source file for the HC-SR04 (ultrasonic sensor) driver
 *
 * Author: Esraa Ali
 *
 *******************************************************************************/
/* include the header file of the used driver*/
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include "common_macros.h"
#include <util/delay.h> /*include delay function*/

/*for variable : g is refer to -> global*/
static uint16 g_distance;
static uint16 g_time;
static uint8 g_edges_counter;

/*
 *  Description :1- Initialize the ICU driver as required.
                 2- Setup the ICU call back function.
                 3- Setup the direction for the trigger pin as output pin through the GPIO driver.
     Inputs      : None
     Return      : None
 * */
void Ultrasonic_init(void){
	/*
	 * setup the icu : 1- frequency -> fcpu/8
	 *                 2- start with first rising edge
	 * */
	Icu_ConfigType icu_type={F_CPU_8,RISING};
	Icu_init(&icu_type);
	/*call back by passing the address of the edge processing function
	 *  (name of the function = address of the function )*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* setup the direction of the trigger to be output pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORTID,ULTRASONIC_TRIGGER_PINID,PIN_OUTPUT);
}


/*
• Description : Send the Trigger pulse to the ultrasonic.
• Inputs      : None
• Return      : None
 */
void Ultrasonic_Trigger(void){
	/*give the trigger logic high (1) to start send signal */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORTID,ULTRASONIC_TRIGGER_PINID,LOGIC_HIGH);
	/*delay for sending signal*/
	_delay_ms(10);
	/*give the trigger logic low (0) to stop send signal */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORTID,ULTRASONIC_TRIGGER_PINID,LOGIC_LOW);
}

/*
• Description : 1-Send the trigger pulse by using Ultrasonic_Trigger function.
                2-Start the measurements by the ICU from this moment.
• Inputs      : None
• Return      : The measured distance in Centimete
 */
uint16 Ultrasonic_readDistance(void){
	/* sending pulses by the trigger*/
	Ultrasonic_Trigger();
	if(g_edges_counter==2){ //raising & falling -> 1 cycle
		g_edges_counter=0; //reset the counter of the edges
		/* equation to convert from time to distance*/
		g_distance = (g_time*0.01715);
	}
	return (g_distance+1);
}

/*
   Description : 1-This is the call back function called by the ICU driver.
               : 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
   Inputs      : None
   Return      : None
 */

void Ultrasonic_edgeProcessing(void){
	/*increment the edge by one */
	g_edges_counter++;
	if(g_edges_counter==1){
		/*clear the timer register to start the timer when the rising edge is detected*/
		Icu_clearTimerValue();
		/*change the edge select to the falling edge to know the time of the pulse*/
		Icu_setEdgeDetectionType(FALLING);
	}
	/*this condition will be true when the falling edge is detected*/
	else if(g_edges_counter==2){
		/*we will read the input capture register and save it inside the g_timeHigh*/
		g_time = Icu_getInputCaptureValue();

		/*clear the input capture register to start detect again*/
		Icu_clearTimerValue();

		/*To start detecting from the rising edge*/
		Icu_setEdgeDetectionType(RISING);
	}
}

